name: Build and Deploy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: 
      - '**'  # Trigger on all branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'
    - name: Load variables
      run: |
        touch .env
        echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
        echo EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }} >> .env
        echo EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} >> .env
        echo BE_URL=${{ secrets.BE_URL }} >> .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
        echo FE_URL=${{ secrets.FE_URL }} >> .env
        echo BASE_PATH_PREFIX=${{ secrets.BASE_PATH_PREFIX }} >> .env
        echo DOMAIN_SERVICE_PATH=${{ secrets.DOMAIN_SERVICE_PATH }} >> .env
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build

  deploy:
    if: github.ref == 'refs/heads/main'  # Only run on main branch
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          export NVM_DIR="/home/kanzen/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 20

          cd /home/kanzen/Hiji-be
          git reset --hard HEAD
          git pull origin main --rebase
          npm install
          npm run build
          pm2 restart hiji-be:service