name: Build and Deploy

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: 
      - '**'  # Trigger on all branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'
    - name: Load variables
      run: |
        touch .env
        echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
        echo EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }} >> .env
        echo EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} >> .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
        echo BE_URL=${{ vars.BE_URL }} >> .env
        echo FE_URL=${{ vars.FE_URL }} >> .env
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build

  deploy:
    if: github.ref == 'refs/heads/main'  # Only run on main branch
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/rahman/BE_skillpractice
          git reset --hard HEAD
          git pull origin main --rebase
          npm install
          npm run build          
          sudo systemctl restart hiji-be.service